{
  description = "SlackIn2Zammad";

  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs";
  };

  outputs = { self, nixpkgs }:
    let

      allSystems = [
        "x86_64-linux"
        "aarch64-linux"
        "x86_64-darwin"
        "aarch64-darwin"
      ];

      forAllSystems = f: nixpkgs.lib.genAttrs allSystems (system: f {
        pkgs = import nixpkgs { inherit system; };
      });
    in
      {
      devShells = forAllSystems ({ pkgs }: {
        default =
          let
            packageOverrides = pkgs.callPackage ./python-packages.nix { };
            python = pkgs.python312.override { inherit packageOverrides; };

          in
            pkgs.mkShell {
              packages = [
                (python.withPackages (ps: with ps; [

                  # These are generated by pip2nix
                  slack-bolt
                  zammadoo
                  python-dotenv

                  # packages from nixpkgs are supported as well
                ]))
              ];
            };
      });
    };
}
